# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06bf6f79ab477751da5c25a78c74b5978951a9c1123ee5115273eff8f629ef9a093520451a5ecd1d0b91d676708ca38589bef12140252e08b01271a5a3f989db

test:
  secret_key_base: 4bb9b27d58fe4472fc15fe514bdcd590bb609f2fec2bb9e83886ac84a6225b8ef56209dcd68d1fd9b26a9218aeb3360afab847c098a0b3bfe8423d9b9ebe4740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
